---
title: "Capstone_exercise"
output: html_document
---

```{r,load_libraries, echo=FALSE, results="hide", message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
```

```{r, load_data,echo=FALSE}
gapminder <- read.csv("gapminder.csv")
```

scatter plots (one for each country) that has year on the x-axis and GDP on the y axis

```{r, plot_data_3countries, echo=FALSE}
data <- gapminder %>% filter(country== "China"|country=="United States"|country== "Albania") 
ggplot(data,aes (x=year, y=gdpPercap)) +
  geom_point() +
  facet_grid(~country)
```

comments on the graphs
------------------
-------------
---  

```{r, continent_stat, echo=FALSE}
gapminder %>%
  group_by(continent, year=2007) %>%
  summarize(meanlifeExp = mean(lifeExp), minlifeExp= min(lifeExp),maxlifeExp=max(lifeExp))
```


comments on the stat
------------------
-------------
---  

```{r, plot_data_histograms, echo=FALSE}
ggplot(gapminder,aes (x=lifeExp)) +
  geom_histogram(fill="lightblue", color="black")

ggplot(gapminder,aes (x=lifeExp)) +
  geom_histogram(binwidth=1.5, fill="lightblue", color="black")
```

comments on the stat
------------------
-------------
---  



